// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * PR Reviewer Assignment Service (Test Task, Fall 2025)
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package server




type UsersSetIsActivePostRequest struct {

	UserId string `json:"user_id"`

	IsActive bool `json:"is_active"`
}

// AssertUsersSetIsActivePostRequestRequired checks if the required fields are not zero-ed
func AssertUsersSetIsActivePostRequestRequired(obj UsersSetIsActivePostRequest) error {
	elements := map[string]interface{}{
		"user_id": obj.UserId,
		"is_active": obj.IsActive,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertUsersSetIsActivePostRequestConstraints checks if the values respects the defined constraints
func AssertUsersSetIsActivePostRequestConstraints(obj UsersSetIsActivePostRequest) error {
	return nil
}
