// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * PR Reviewer Assignment Service (Test Task, Fall 2025)
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package server




type PullRequestMergePostRequest struct {

	PullRequestId string `json:"pull_request_id"`
}

// AssertPullRequestMergePostRequestRequired checks if the required fields are not zero-ed
func AssertPullRequestMergePostRequestRequired(obj PullRequestMergePostRequest) error {
	elements := map[string]interface{}{
		"pull_request_id": obj.PullRequestId,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertPullRequestMergePostRequestConstraints checks if the values respects the defined constraints
func AssertPullRequestMergePostRequestConstraints(obj PullRequestMergePostRequest) error {
	return nil
}
