// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * PR Reviewer Assignment Service (Test Task, Fall 2025)
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package main

import (
	"log"
	"net/http"

	server "github.com/GIT_USER_ID/GIT_REPO_ID/go"
)

func main() {
	log.Printf("Server started")

	PullRequestsAPIService := server.NewPullRequestsAPIService()
	PullRequestsAPIController := server.NewPullRequestsAPIController(PullRequestsAPIService)

	TeamsAPIService := server.NewTeamsAPIService()
	TeamsAPIController := server.NewTeamsAPIController(TeamsAPIService)

	UsersAPIService := server.NewUsersAPIService()
	UsersAPIController := server.NewUsersAPIController(UsersAPIService)

	router := server.NewRouter(PullRequestsAPIController, TeamsAPIController, UsersAPIController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
